language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - nosetests --with-coverage
after_success:
  - codecov
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi # Remove for deployment to official PyPi repo
  user: "Your username"
  password: "Your password"
  on:
    branch: deploy
    tags: true
