language: python
python:
- '3.4'
- '3.5'
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- nosetests --with-coverage test/*
- flake8
after_success:
- codecov
jobs:
  include:
  - stage: release
    python: '3.6'
    deploy:
      provider: pypi
      server: https://test.pypi.org/legacy/
      user: jnkm
      password:
        secure: IDzZS7+ypRDdOkUYDOfJ6yMzn+b5vwedOXVmrRxNC/qW3LCb0uFD4bT0uxgwMEzsiFpBFXnrW3oBszNpL/9A/yLmjXKvfmy9kl8iEAUEaqFgKVeYnCRtnyU7JK4LfmaZfINqf8gv0rWbDJ/p8bUgZoS6H3XBwyAm5xy9wRj81GO0HgaNvDn4e1gCxLz+LH4phYom3oCKGHHvD0i9/EU7ljoFGLFYWM2skS51Gq7mlUJ+w69LS94LBeLljwW73TzJs6r9Whrgxh5J/OReyuH7jwuYyIoFoV4d9iS/GZelKePPVIn4ZXd5rYvrBTBaHMZYAaNc7BrlAYNzbXLaIUlCWmeK8tUr0D11n37IP/XXbZh0W/Au4oQ/If0G3wdQwoLJ/h4ZlcB7HvWmH2KXarsiGIeJHFfCqKE++J2WXRBZUXqPEN6ATIvCc7NqcxBj2vcU5xbJ7Jt/6fLkKmAoyO4prTdv7SV/N4wujMkh2dHk+HG3uCpchrU3TAFVA/USCQyM4OHo0VOUvQCKErOaKh5HqALg6givEPDUvQce6gHPjeTcjamXj1FLsmt1db1/MXOXy3ttn1sxRktHZ7rY8wDiKR8y4hTMiWYigsG6InRev432XAOASQh5EEOmZhM80LZ0foqfKVSCCPpd2WxM1U/phFMm0YXg3tcOjsNUNVYPaps=
      on:
        branch: master
deploy:
  password:
    secure: kuRnH4GlvifWFQC+ltFMjxmx2gGfXu3kyH98meOvhq6pdo81UglCcuplVe+Z7jZx2s0Mljx7vFBSkzfxe/jBfYVTLGDNYMJ0YWnAkhOBvjVvxkr5OSZ0+QLyC5GGSG6c0pduQigwwiMOID+B+7k5347nyp2JsoUGH9FWMljB35WBI7bFiD2LU6AFHm4POdpnJ+RSgzcDGyGghsvS1Pk3k2IYFBWnTuSmq5kkItO8KRoTlEd4YGd6ZzuqqHnrVnrfSlfPCNGSJQn2CK8s5B4j34WeK87hRjnrP50qfUG+J/HRLMNXt79YFpgnlFw224Hf4gTUTIZU8gQMje8wb7mLsclSdkn2paFn+Rj9LnrS8DHeNE26IgowrBFpWRVNbNWDut3oFBj1uIMCKt9ctvf3VNMW83Jv+G5JcFq8wgkspqxrVa3HTkAHIPGrtc40LryzWBapL+2e/IvLDSv/AG9fH09RnHk51qIkxvvDVT/OnmU8g/WqZfS/oJMoSI0sceI/B0THqx1kerNtvezHNlVtsNAutwU3F81uQ3/sWCGEnLIccdfxniZJjdk5grSuKflYOUhzSdbnwYJmCmia63YU7ussed19Z3EVQ3/AE/a5SgET+O0Vo+SRBEBlNr/e7iPPsxAMYRClBap1TPsnqSCHy1CnRhSqFccuzlRnyvsW5Cg=
