language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install codecov
script:
  - nosetests --with-coverage
after_success:
  - codecov
