language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage
after_success:
  - bash < (curl -s https://codecov.io/bash)
